import React from 'react'
import { useNavigate } from 'react-router-dom'
import { motion } from 'framer-motion'
import { Sparkles, Bot, Calendar, Target, Heart, Star } from 'lucide-react'

const features = [
  { icon: <Bot className="w-8 h-8" />, color: 'text-purple-400', title: 'AI-Powered Plans', desc: 'Get personalized workout and nutrition plans generated by advanced AI tailored to your body and goals.' },
  { icon: <Calendar className="w-8 h-8" />, color: 'text-blue-400', title: 'Smart Scheduling', desc: 'Automatic Google Calendar integration for seamless plan management and workout reminders.' },
  { icon: <Target className="w-8 h-8" />, color: 'text-orange-400', title: 'Goal Tracking', desc: 'Track your progress with detailed analytics, charts, and achievement badges to stay motivated.' },
  { icon: <Heart className="w-8 h-8" />, color: 'text-green-400', title: 'Charity Impact', desc: 'Turn your fitness journey into charitable donations automatically. Every workout counts!' },
]

const testimonials = [
  { name: 'Priya Sharma', role: 'Software Engineer', text: "ArogyaMitra transformed my fitness journey! The AI plans are spot-on and the charity aspect keeps me motivated. Love the Indian meal plans! 🙏", stars: 5 },
  { name: 'Rahul Kumar', role: 'Student', text: "Love how it syncs with my Google Calendar. Never miss a workout now! The AROMI coach feels like talking to a real trainer. 💪", stars: 5 },
  { name: 'Anita Patel', role: 'Doctor', text: "The nutrition plans are scientifically sound and easy to follow. Highly recommended for anyone looking to improve their health! ⭐", stars: 5 },
]

const stats = [
  { value: '10K+', label: 'Active Users' },
  { value: '50K+', label: 'Workouts Completed' },
  { value: '₹2L+', label: 'Raised for Charity' },
  { value: '95%', label: 'Success Rate' },
]

const fadeUp = { hidden: { opacity: 0, y: 30 }, visible: { opacity: 1, y: 0 } }
const stagger = { hidden: {}, visible: { transition: { staggerChildren: 0.12 } } }
const scaleIn = { hidden: { opacity: 0, scale: 0.85 }, visible: { opacity: 1, scale: 1 } }

export default function Landing() {
  const navigate = useNavigate()
  return (
    <div className="min-h-screen bg-[#0d0d14]">
      {/* Navbar */}
      <nav className="fixed top-0 left-0 right-0 z-50 bg-[#0d0d14]/90 backdrop-blur-sm border-b border-[#2a2a40]">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 flex items-center justify-between h-16">
          <div className="flex items-center gap-2">
            <Sparkles className="w-6 h-6 text-purple-400" />
            <span className="text-xl font-bold text-white">ArogyaMitra</span>
          </div>
          <div className="hidden md:flex items-center gap-6">
            <a href="#features" className="text-gray-400 hover:text-white text-sm transition">Features</a>
            <a href="#reviews" className="text-gray-400 hover:text-white text-sm transition">Reviews</a>
          </div>
          <div className="flex items-center gap-3">
            <button onClick={() => navigate('/login')}
              className="text-gray-300 hover:text-white px-4 py-2 text-sm transition">
              Login
            </button>
            <button onClick={() => navigate('/register')}
              className="bg-green-600 hover:bg-green-700 text-white px-5 py-2 rounded-lg text-sm font-medium transition">
              Get Started
            </button>
          </div>
        </div>
      </nav>

      {/* Hero */}
      <section className="pt-32 pb-20 px-4 text-center relative overflow-hidden">
        <div className="absolute top-0 left-1/2 -translate-x-1/2 w-[600px] h-[600px] bg-purple-600/10 rounded-full blur-3xl pointer-events-none" />
        <div className="relative z-10 max-w-4xl mx-auto">
          <motion.h1
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.7, ease: 'easeOut' }}
            className="text-5xl md:text-7xl font-extrabold mb-6 leading-tight"
          >
            <span className="text-white">Your AI Fitness</span><br />
            <span className="bg-gradient-to-r from-purple-400 to-green-400 bg-clip-text text-transparent">Companion</span>
          </motion.h1>
          <motion.p
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.7, delay: 0.2 }}
            className="text-gray-400 text-lg md:text-xl max-w-2xl mx-auto mb-10 leading-relaxed"
          >
            Transform your health journey with personalized AI-powered workout plans, nutrition guidance, and automatic charity donations. Join thousands who've already started their transformation!
          </motion.p>

          {/* Stats */}
          <motion.div
            initial="hidden" animate="visible"
            variants={stagger}
            className="grid grid-cols-2 md:grid-cols-4 gap-4 max-w-3xl mx-auto mb-10"
          >
            {stats.map((s, i) => (
              <motion.div key={i} variants={scaleIn}
                className="bg-[#1a1a2e] border border-[#2a2a40] rounded-xl p-4"
              >
                <p className="text-2xl font-bold text-purple-400">{s.value}</p>
                <p className="text-gray-400 text-xs mt-1">{s.label}</p>
              </motion.div>
            ))}
          </motion.div>

          <motion.button
            initial={{ opacity: 0, scale: 0.9 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ delay: 0.5, duration: 0.5 }}
            whileHover={{ scale: 1.05 }}
            whileTap={{ scale: 0.95 }}
            onClick={() => navigate('/register')}
            className="bg-gradient-to-r from-purple-600 to-green-600 hover:from-purple-700 hover:to-green-700 text-white px-10 py-4 rounded-xl text-lg font-semibold transition shadow-lg shadow-purple-500/20"
          >
            Start Free Journey →
          </motion.button>
        </div>
      </section>

      {/* Features */}
      <section id="features" className="py-20 px-4">
        <div className="max-w-6xl mx-auto">
          <h2 className="text-3xl md:text-4xl font-bold text-white text-center mb-4">Why Choose ArogyaMitra?</h2>
          <p className="text-gray-400 text-center mb-12 max-w-lg mx-auto">Everything you need for a healthy, happy life — powered by AI</p>
          <motion.div
            initial="hidden" whileInView="visible" viewport={{ once: true, margin: '-50px' }}
            variants={stagger}
            className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6"
          >
            {features.map((f, i) => (
              <motion.div key={i} variants={fadeUp}
                className="bg-[#1a1a2e] border border-[#2a2a40] rounded-xl p-6 hover:border-purple-500/50 transition group"
                whileHover={{ y: -5 }}
              >
                <div className={`${f.color} mb-4 group-hover:scale-110 transition`}>{f.icon}</div>
                <h3 className="text-white font-semibold text-lg mb-2">{f.title}</h3>
                <p className="text-gray-400 text-sm leading-relaxed">{f.desc}</p>
              </motion.div>
            ))}
          </motion.div>
        </div>
      </section>

      {/* Testimonials */}
      <section id="reviews" className="py-20 px-4 bg-[#13131f]">
        <div className="max-w-6xl mx-auto">
          <h2 className="text-3xl md:text-4xl font-bold text-white text-center mb-12">What Our Users Say</h2>
          <motion.div
            initial="hidden" whileInView="visible" viewport={{ once: true, margin: '-50px' }}
            variants={stagger}
            className="grid grid-cols-1 md:grid-cols-3 gap-6"
          >
            {testimonials.map((t, i) => (
              <motion.div key={i} variants={fadeUp}
                className="bg-[#1a1a2e] border border-[#2a2a40] rounded-xl p-6"
                whileHover={{ y: -3 }}
              >
                <div className="flex gap-1 mb-3">
                  {Array.from({ length: t.stars }).map((_, j) => (
                    <Star key={j} className="w-4 h-4 text-yellow-400 fill-yellow-400" />
                  ))}
                </div>
                <p className="text-gray-300 text-sm mb-4 leading-relaxed italic">"{t.text}"</p>
                <div>
                  <p className="text-white font-semibold">{t.name}</p>
                  <p className="text-gray-400 text-xs">{t.role}</p>
                </div>
              </motion.div>
            ))}
          </motion.div>
        </div>
      </section>

      {/* Final CTA */}
      <section className="py-20 px-4 text-center">
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6 }}
          className="max-w-2xl mx-auto"
        >
          <h2 className="text-3xl md:text-4xl font-bold text-white mb-4">Ready to Transform Your Life?</h2>
          <p className="text-gray-400 mb-8">Start your AI-powered fitness journey today — it's free!</p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <motion.button whileHover={{ scale: 1.05 }} whileTap={{ scale: 0.95 }}
              onClick={() => navigate('/register')}
              className="bg-gradient-to-r from-purple-600 to-green-600 hover:from-purple-700 hover:to-green-700 text-white px-8 py-3 rounded-xl font-semibold transition">
              Start Your Journey ✨
            </motion.button>
            <motion.button whileHover={{ scale: 1.05 }} whileTap={{ scale: 0.95 }}
              onClick={() => navigate('/login')}
              className="border border-[#2a2a40] text-gray-300 hover:text-white hover:border-purple-500 px-8 py-3 rounded-xl font-semibold transition">
              Already a Member? →
            </motion.button>
          </div>
        </motion.div>
      </section>

      {/* Footer */}
      <footer className="bg-[#1a1a2e] border-t border-[#2a2a40] py-8 px-4 text-center">
        <p className="text-gray-400 text-sm mb-2">
          <span className="text-purple-400 font-semibold">ArogyaMitra</span> — Your AI Fitness Companion
        </p>
        <p className="text-gray-500 text-xs">Free to start • No credit card required • Cancel anytime</p>
      </footer>
    </div>
  )
}